### ISSUE TITLE
Hugo to YASSG

### ISSUE THREAD

**Issue by brankol** [sigwinhq/yassg#84]
### Global config

Hugo: `{{ .Site.Title }}`
Twig: `{{ site.title }}`

After adding `config/twig.yaml`:

```
twig:
    globals:
        site:
            title: Sigwin
```
